// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FuncFlat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from FuncFlat.proto</summary>
public static partial class FuncFlatReflection {

  #region Descriptor
  /// <summary>File descriptor for FuncFlat.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FuncFlatReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg5GdW5jRmxhdC5wcm90byJCCghGbGF0RnVuYxIUCgxmdW5jdGlvbk5hbWUY",
          "ASABKAkSDwoHZGxsTmFtZRgCIAEoCRIPCgdkbGxQYXRoGAMgASgJYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::FlatFunc), global::FlatFunc.Parser, new[]{ "FunctionName", "DllName", "DllPath" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class FlatFunc : pb::IMessage<FlatFunc> {
  private static readonly pb::MessageParser<FlatFunc> _parser = new pb::MessageParser<FlatFunc>(() => new FlatFunc());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<FlatFunc> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FuncFlatReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FlatFunc() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FlatFunc(FlatFunc other) : this() {
    functionName_ = other.functionName_;
    dllName_ = other.dllName_;
    dllPath_ = other.dllPath_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public FlatFunc Clone() {
    return new FlatFunc(this);
  }

  /// <summary>Field number for the "functionName" field.</summary>
  public const int FunctionNameFieldNumber = 1;
  private string functionName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string FunctionName {
    get { return functionName_; }
    set {
      functionName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "dllName" field.</summary>
  public const int DllNameFieldNumber = 2;
  private string dllName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DllName {
    get { return dllName_; }
    set {
      dllName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "dllPath" field.</summary>
  public const int DllPathFieldNumber = 3;
  private string dllPath_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string DllPath {
    get { return dllPath_; }
    set {
      dllPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as FlatFunc);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(FlatFunc other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (FunctionName != other.FunctionName) return false;
    if (DllName != other.DllName) return false;
    if (DllPath != other.DllPath) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (FunctionName.Length != 0) hash ^= FunctionName.GetHashCode();
    if (DllName.Length != 0) hash ^= DllName.GetHashCode();
    if (DllPath.Length != 0) hash ^= DllPath.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (FunctionName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(FunctionName);
    }
    if (DllName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(DllName);
    }
    if (DllPath.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(DllPath);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (FunctionName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(FunctionName);
    }
    if (DllName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DllName);
    }
    if (DllPath.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DllPath);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(FlatFunc other) {
    if (other == null) {
      return;
    }
    if (other.FunctionName.Length != 0) {
      FunctionName = other.FunctionName;
    }
    if (other.DllName.Length != 0) {
      DllName = other.DllName;
    }
    if (other.DllPath.Length != 0) {
      DllPath = other.DllPath;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          FunctionName = input.ReadString();
          break;
        }
        case 18: {
          DllName = input.ReadString();
          break;
        }
        case 26: {
          DllPath = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
